### ISSUE TITLE
Disable server host name verification

### ISSUE THREAD

**Issue by adrian-vlad** [SourceLabOrg/kafka-webview#221]
Is it possible to disable the SSL server host name verification?
Basically, the behavior of **ssl.endpoint.identification.algorithm** with empty value.

**Comment by Crim** [comment]
Hi,

At the current time it is not possible to set this property.  Rather than solving specifically for your configuration property, I think it probably makes sense to expose a new section under the cluster configuration in kafka-webview that allows setting adhoc client properties.  You could then use this section to define whatever additional properties you may need.

What do you think?

**Comment by adrian-vlad** [comment]
Yes, it's fine. As long as it gets the job done. It might be useful for other options that are not currently supported, although I cannot think of any at the moment.

**Comment by Crim** [comment]
This should be included in the next release.
